---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
    - containerPort: 80
      hostPort: 80
      listenAddress: 0.0.0.0
    - containerPort: 443
      hostPort: 443
      listenAddress: 0.0.0.0
containerdConfigPatches:
  - |-
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://registry.local:5000"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.local:5000"]
      endpoint = ["http://registry.local:5000"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."example.com"]
      endpoint = ["http://registry.local:5000"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."example.org"]
      endpoint = ["http://registry.local:5000"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."test.com"]
      endpoint = ["http://registry.local:5000"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."test.org"]
      endpoint = ["http://registry.local:5000"]
