apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/redhat-scholars/tekton-tutorial-greeter
    - name: revision
      value: staging
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tekton-tutorial-greeter-image
spec:
  type: image
  params:
    - name: url
      # use KinD internal registry
      value: registry.local:5000/rhdevelopers/tekton-tutorial-greeter
      # if you are on OpenShift, use OpenShift interal registry
      #value: "image-registry.openshift-image-registry.svc:5000/tektontutorial/greeter"
