name: Tekton Tutorial Staging

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  SITE_DIR: 'gh-pages'
  STAGING_REPO: 'redhat-developer-demos/tekton-tutorial-staging'
  STAGING_SITE_PLAYBOOK: 'staging.yml'
jobs:
  stagingSite:
    name: Build and Deploy Staging Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Site
        uses: kameshsampath/antora-site-action@v0.2.4
        with:
          antora_playbook: "${{ env.STAGING_SITE_PLAYBOOK }}"
      - name: List Directory 
        run: |
          ls -ltr "${{ github.workspace }}"
          ls -ltr "${{ env.SITE_DIR }}"
      - name: Deploy Site
        id: deploy_site
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: "${{ secrets.TKN_STAGING_SITE_DEPLOY }}"
          publish_dir: "${{ env.SITE_DIR }}"
          publish_branch: "gh-pages"
          external_repository: redhat-developer-demos/tekton-tutorial-staging
          full_commit_message: ${{ github.event.head_commit.message }}
      - uses: GoogleCloudPlatform/release-please-action@v2.7.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          bump-minor-pre-major: true